spring:
  application:
    name: ${APPLICATION_NAME:testme}
  datasource:
    #配置数据库连接地址
    url: ${DATASOURCE_URL:jdbc:mysql://rm-wz97r87bwuro0g5a66o.mysql.rds.aliyuncs.com:3306/elsi-trunk?useUnicode=true&characterEncoding=utf-8}
    username: ${DATASOURCE_USERNAMR:elsi-trunk}
    password: ${DATASOURCE_PASSWORD:imcsoft.12345}
  redis:
    host: redis
    port: 6379
    timeout: 16000
    password:
    database: 0
  rabbitmq:
    #是否启用
    enable: true
    #服务地址
    host: rabbitmq
    port: 5672
    username: imcsoft
    password: iotimc.12345
    publisher-confirm: true
    virtual-host: /
    default-topic: command
config:
  #移动物联网接入平台
  onenet:
    #onenet平台请求地址
    url: http://api.heclouds.com
    #在onenet平台上获取的api请求key,用于发生请求
    apikey: kpMtwVo=0aHfrk4nBtuDDC29Msg=
    #消息加解密秘钥
    encodingAESKey: b47dm2OmFyFkiRySbE8GZQ1tDxxGnc23NyT2A2NLMHT
    #验证token
    token: iotimc
    #使用的是ws还是es
    sockettype: es
    #发送失败重试次数
    retry: 6
  product-type: 1
  lwm2mmapping: nblamp3.0
  qrCodeKey: IOTIMCIOTIMCIOTI
server:
  port: ${SERVER_PORT:8809}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_LIST:http://iotimc:imcsoft.12345@eserver.iotdev.top/eureka}
elsi:
  swagger:
    #文档标题
    title:
    #文档描述
    description:
    #文档版本号
    version: 1.0
  mode: ${ELSI_MODE:dev}
  #配置云端的地址信息
  remote:
    #云端网关地址
    gateway: ${ELSI_REMOTE_GATEWAY:api.iotdev.top/admin}
config:
  onenet:
    retry: 6
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      enabled: true
      sensitive: false
    shutdown:
      enabled: true
logging:
  file: ${LOGGER_HOME}/manager/logs/log.log