spring:
  application:
    name: ${APPLICATION_NAME:testme}
  datasource:
    #配置数据库连接地址
    url: ${DATASOURCE_URL:jdbc:mysql://rm-wz97r87bwuro0g5a66o.mysql.rds.aliyuncs.com:3306/elsi-trunk?useUnicode=true&characterEncoding=utf-8}
    username: ${DATASOURCE_USERNAMR:elsi-trunk}
    password: ${DATASOURCE_PASSWORD:imcsoft.12345}
  redis:
    host: redis
    port: 6379
    timeout: 16000
    password: 123456
    database: 0
  rocketmq:
    #是否启用
    enable: true
    #服务地址
    namesrvAddr: namesrv:9876
    #普通生产者组名
    producerGroupName: producerGroup
    #事务生产者组名
    transactionProducerGroupName: onenetTran
    #消费者组名
    consumerGroupName: consumerGroup
    #生产者实例名
    producerInstanceName: producerIns
    #消费者实例名
    consumerInstanceName: consumerIns
    #事务生产者实例名
    producerTranInstanceName: producerTranIns
    #一次最大消费消息量
    consumerBatchMaxSize: 200
    #广播消费
    consumerBroadcasting: false
    #主题名
    subscribe[0]: onenet
    #是否在启动时处理历史记录
    enableHisConsumer: false
    #是否启动顺序消费
    enableOrderConsumer: false
server:
  port: ${SERVER_PORT:8809}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_LIST:http://iotimc:imcsoft.12345@eserver.iotdev.top/eureka}
elsi:
  swagger:
    #文档标题
    title:
    #文档描述
    description:
    #文档版本号
    version: 1.0
  mode: ${ELSI_MODE:dev}
  #配置云端的地址信息
  remote:
    #云端网关地址
    gateway: ${ELSI_REMOTE_GATEWAY:api.iotdev.top/admin}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      enabled: true
      sensitive: false
    shutdown:
      enabled: true
logging:
  file: ${LOGGER_HOME}/manager/logs/log.log